version: '2'
services:
  nanobench:
    image: nanopub/nanobench
    restart: unless-stopped
    ports:
      - 7901:8080
#    environment:
#      - NANOBENCH_API_INSTANCES=http://grlc.nanopubs.lod.labs.vu.nl/api/local/local/ http://130.60.24.146:7881/api/local/local/
